<a href="https://colab.research.google.com/github/sampada-11/Data_Science_Lab/blob/main/exp_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:

#Create a 3x3 square matrix and compute its determinant.(WITHOUT NUMPY)

def determinant_3x3(matrix):
    """
    Calculate determinant of 3x3 matrix using the formula:
    det = a(ei − fh) − b(di − fg) + c(dh − eg)
    """
    a = matrix[0][0]
    b = matrix[0][1]
    c = matrix[0][2]
    d = matrix[1][0]
    e = matrix[1][1]
    f = matrix[1][2]
    g = matrix[2][0]
    h = matrix[2][1]
    i = matrix[2][2]

    det = (a * (e * i - f * h) -
           b * (d * i - f * g) +
           c * (d * h - e * g))

    return det

# Take user input for 3x3 matrix
print("Enter elements of 3x3 matrix row by row:")
matrix = []

for i in range(3):
    row = []
    print(f"Enter row {i+1} (3 numbers separated by space):")
    row_input = input().strip().split()

    # Convert strings to floats
    for num in row_input:
        row.append(float(num))

    matrix.append(row)

# Display the matrix
print("\nYour 3x3 matrix:")
for row in matrix:
    print(row)

# Calculate and display determinant
det = determinant_3x3(matrix)
print(f"\nDeterminant = {det}")

Enter elements of 3x3 matrix row by row:
Enter row 1 (3 numbers separated by space):
1 2 3 
Enter row 2 (3 numbers separated by space):
4 5 6
Enter row 3 (3 numbers separated by space):
3 2 1

Your 3x3 matrix:
[1.0, 2.0, 3.0]
[4.0, 5.0, 6.0]
[3.0, 2.0, 1.0]

Determinant = 0.0


In [ ]:
import numpy as np

# Create a 3x3 matrix by taking input from the user(WITH NUMPY)
matrix_elements = []
print("Enter the elements of the 3x3 matrix row by row (press Enter after each element):")
for i in range(3):
    row = []
    for j in range(3):
        while True:
            try:
                element = float(input(f"Enter element [{i+1}][{j+1}]: "))
                row.append(element)
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
    matrix_elements.append(row)

numpy_matrix = np.array(matrix_elements)

print("NumPy 3x3 Matrix:")
print(numpy_matrix)

# Compute the determinant using NumPy
numpy_determinant = np.linalg.det(numpy_matrix)

print(f"\nDeterminant of the NumPy matrix : {numpy_determinant}")

Enter the elements of the 3x3 matrix row by row (press Enter after each element):
Enter element [1][1]: 2
Enter element [1][2]: 3
Enter element [1][3]: 1
Enter element [2][1]: 1
Enter element [2][2]: 4
Enter element [2][3]: 6
Enter element [3][1]: 3
Enter element [3][2]: 1
Enter element [3][3]: 2
NumPy 3x3 Matrix:
[[2. 3. 1.]
 [1. 4. 6.]
 [3. 1. 2.]]

Determinant of the NumPy matrix : 41.00000000000001


In [8]:
#Find the inverse of the matrix.(WITHOUT NUMPY)
def determinant_3x3(matrix):
    """Calculate determinant of 3x3 matrix"""
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    return (a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g))

def adjoint_3x3(matrix):
    """Calculate adjoint (adjugate) matrix"""
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    # Cofactor matrix
    cofactor = [
        [e*i - f*h, -(d*i - f*g), d*h - e*g],
        [-(b*i - c*h), a*i - c*g, -(a*h - b*g)],
        [b*f - c*e, -(a*f - c*d), a*e - b*d]
    ]

    # Transpose to get adjoint
    adjoint = [
        [cofactor[0][0], cofactor[1][0], cofactor[2][0]],
        [cofactor[0][1], cofactor[1][1], cofactor[2][1]],
        [cofactor[0][2], cofactor[1][2], cofactor[2][2]]
    ]

    return adjoint

def inverse_3x3(matrix):
    """Calculate inverse = (1/det) * adjoint"""
    det = determinant_3x3(matrix)

    if abs(det) < 1e-10:  # Check if singular matrix
        return None

    adj = adjoint_3x3(matrix)

    # Multiply adjoint by 1/determinant
    inv = []
    for i in range(3):
        row = []
        for j in range(3):
            row.append(adj[i][j] / det)
        inv.append(row)

    return inv

# Take user input for 3x3 matrix
print("Enter elements of 3x3 matrix row by row:")
matrix = []

for i in range(3):
    print(f"Enter row {i+1} (3 numbers separated by space):")
    row = list(map(int, input().strip().split())) # Changed float to int
    matrix.append(row)

print("\nYour matrix:")
for row in matrix:
    print(f"  {row[0]:6d} {row[1]:6d} {row[2]:6d}") # Changed float formatting to int

# Calculate inverse
inverse_matrix = inverse_3x3(matrix)

if inverse_matrix is None:
    print("\n Matrix is singular (determinant = 0). No inverse exists!")
else:
    print("\n Inverse matrix:")
    for row in inverse_matrix:
        print(f"  {row[0]:6.2f} {row[1]:6.2f} {row[2]:6.2f}")

Enter elements of 3x3 matrix row by row:
Enter row 1 (3 numbers separated by space):
5 2 8
Enter row 2 (3 numbers separated by space):
7 4 1 
Enter row 3 (3 numbers separated by space):
9 6 3

Your matrix:
       5      2      8
       7      4      1
       9      6      3

 Inverse matrix:
    0.11   0.78  -0.56
   -0.22  -1.06   0.94
    0.11  -0.22   0.11


In [9]:
#Solve the following system of linear equations: 2x+3y=10, 4x+5y=20(WITHOUT NUMPY)
def solve_2x2_system(a1, b1, c1, a2, b2, c2):
    """
    Solve: a1*x + b1*y = c1
           a2*x + b2*y = c2
    """
    # Using Cramer's Rule (super simple!)
    det = a1*b2 - a2*b1

    if abs(det) < 1e-10:
        return None  # No unique solution

    x = (c1*b2 - c2*b1) / det
    y = (a1*c2 - a2*c1) / det

    return x, y

# Take user input
print("Enter coefficients for 2 equations (2x + 3y = 10, 4x + 5y = 20):")
print("Equation 1: a1 b1 c1 (for a1*x + b1*y = c1)")
a1, b1, c1 = map(float, input("Enter a1 b1 c1: ").strip().split())

print("Equation 2: a2 b2 c2 (for a2*x + b2*y = c2)")
a2, b2, c2 = map(float, input("Enter a2 b2 c2: ").strip().split())

# Solve
solution = solve_2x2_system(a1, b1, c1, a2, b2, c2)

if solution is None:
    print("\n No unique solution (determinant = 0)")
else:
    x, y = solution
    print(f"\n Solution:")
    print(f"x = {x:.2f}")
    print(f"y = {y:.2f}")

    # Verify
    print(f"\nVerification:")
    print(f"{a1:.1f}x + {b1:.1f}y = {a1*x + b1*y:.1f} (should be {c1})")
    print(f"{a2:.1f}x + {b2:.1f}y = {a2*x + b2*y:.1f} (should be {c2})")

Enter coefficients for 2 equations (2x + 3y = 10, 4x + 5y = 20):
Equation 1: a1 b1 c1 (for a1*x + b1*y = c1)
Enter a1 b1 c1: 2 3 4
Equation 2: a2 b2 c2 (for a2*x + b2*y = c2)
Enter a2 b2 c2: 4 5 6

 Solution:
x = -1.00
y = 2.00

Verification:
2.0x + 3.0y = 4.0 (should be 4.0)
4.0x + 5.0y = 6.0 (should be 6.0)


In [10]:
import numpy as np
#Solve the following system of linear equations using NumPy: 2x+3y=10, 4x+5y=20


print("Enter coefficients for the system of linear equations:")
print("For equation 1: a1*x + b1*y = c1")
a1 = float(input("Enter a1: "))
b1 = float(input("Enter b1: "))
c1 = float(input("Enter c1: "))

print("\nFor equation 2: a2*x + b2*y = c2")
a2 = float(input("Enter a2: "))
b2 = float(input("Enter b2: "))
c2 = float(input("Enter c2: "))

# Define the coefficient matrix A
A = np.array([[a1, b1], [a2, b2]])

# Define the constant vector b
b = np.array([c1, c2])

print("\nCoefficient Matrix A:")
print(A)
print("\nConstant Vector b:")
print(b)

# Solve the system of equations
try:
    solution_np = np.linalg.solve(A, b)
    x_np, y_np = solution_np
    print(f"\nSolution using NumPy:")
    print(f"x = {x_np:.2f}")
    print(f"y = {y_np:.2f}")

    # Verification
    print(f"\nVerification:")
    print(f"{a1:.1f}x + {b1:.1f}y = {a1*x_np + b1*y_np:.1f} (should be {c1})")
    print(f"{a2:.1f}x + {b2:.1f}y = {a2*x_np + b2*y_np:.1f} (should be {c2})")
except np.linalg.LinAlgError:
    print("\nError: The matrix is singular or ill-conditioned. No unique solution exists.")

Enter coefficients for the system of linear equations:
For equation 1: a1*x + b1*y = c1
Enter a1: 2
Enter b1: 5
Enter c1: 6

For equation 2: a2*x + b2*y = c2
Enter a2: 1
Enter b2: 3
Enter c2: 8

Coefficient Matrix A:
[[2. 5.]
 [1. 3.]]

Constant Vector b:
[6. 8.]

Solution using NumPy:
x = -22.00
y = 10.00

Verification:
2.0x + 5.0y = 6.0 (should be 6.0)
1.0x + 3.0y = 8.0 (should be 8.0)


In [12]:
# Calculate the inverse using NumPy
import numpy as np

# Function to take matrix input from user
def get_matrix_input(rows, cols):
    matrix = []
    print(f"Enter elements of the {rows}x{cols} matrix row by row:")
    for i in range(rows):
        while True:
            try:
                row_input = input(f"Enter row {i + 1} (space-separated numbers): ").strip().split()
                if len(row_input) != cols:
                    raise ValueError(f"Please enter exactly {cols} numbers for row {i + 1}.")
                row = [float(x) for x in row_input]
                matrix.append(row)
                break
            except ValueError as e:
                print(f"Invalid input: {e}. Please try again.")
    return np.array(matrix)

# Get 3x3 matrix input from the user
user_matrix = get_matrix_input(3, 3)

print("\nYour 3x3 matrix:")
print(user_matrix)

# Calculate the inverse using NumPy
try:
    numpy_inverse_matrix = np.linalg.inv(user_matrix)
    print("\nInverse matrix (NumPy):")
    print(numpy_inverse_matrix)

    # Verification (optional: multiply matrix by its inverse to get identity matrix)
    print("\nVerification (Matrix * Inverse - Identity Matrix, should be close to zero):")
    identity_check = np.dot(user_matrix, numpy_inverse_matrix)
    print(identity_check - np.identity(3))

except np.linalg.LinAlgError:
    print("\nError: The matrix is singular, so its inverse cannot be computed.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Enter elements of the 3x3 matrix row by row:
Enter row 1 (space-separated numbers): 2 5 3
Enter row 2 (space-separated numbers): 4 1 6 
Enter row 3 (space-separated numbers): 5 4 8

Your 3x3 matrix:
[[2. 5. 3.]
 [4. 1. 6.]
 [5. 4. 8.]]

Inverse matrix (NumPy):
[[ 1.77777778e+00  3.11111111e+00 -3.00000000e+00]
 [ 2.22222222e-01 -1.11111111e-01 -6.53072367e-17]
 [-1.22222222e+00 -1.88888889e+00  2.00000000e+00]]

Verification (Matrix * Inverse - Identity Matrix, should be close to zero):
[[ 0.00000000e+00  4.44089210e-16  2.22044605e-16]
 [-8.88178420e-16  8.88178420e-16  4.44089210e-16]
 [ 0.00000000e+00  1.77635684e-15 -1.77635684e-15]]
